import { WindowProvider } from "@/utils/WindowContext";
import "../css/globals.css";
import React from "react";

export const metadata = {
  title: "Height Calculator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <WindowProvider>
        <body className={`desktop-bg h-screen`}>{children}</body>
      </WindowProvider>
    </html>
  );
}
